### ISSUE TITLE
Build can't generate executable file

### ISSUE THREAD

**Issue by fcnaud** [instilledbee/MakeLove#1]
Hi, I have a problem when I build your project, all the result is dll file. Is there has some mistake during my build process?

How could I generate a executable file, just like `.exe`.

build output
```
PM> dotnet build
用于 .NET Core 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe
版权所有(C) Microsoft Corporation。保留所有权利。

  C:\Project\_Tools\MakeLove\MakeLove.App\MakeLove.App.csproj 的还原在 42.36 ms 内完成。
  C:\Project\_Tools\MakeLove\MakeLove.Core\MakeLove.Core.csproj 的还原在 42.36 ms 内完成。
  MakeLove.Core -> C:\Project\_Tools\MakeLove\MakeLove.Core\bin\Debug\netcoreapp2.0\MakeLove.Core.dll
  MakeLove.App -> C:\Project\_Tools\MakeLove\MakeLove.App\bin\Debug\netcoreapp2.0\MakeLove.App.dll

已成功生成。
    0 个警告
    0 个错误
```
Sorry for output text in chinese, it's just mean no warning and no wrong.

**Comment by fcnaud** [comment]
It's seems that I use wrong command. The right one shoud be
```
dotnet publish -r win-x64
```
This command line could be generate exe file. If others want to use maybe need change some paramater.

more info https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by instilledbee** [comment]
Yes you will need to run `dotnet publish`. Thanks for pointing it out. I will update the README accordingly.
